// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: audiobook.
// - Entity ID: 102019c0fdf131574d48997076a9546a8eb.
// - Entity Version: 102019c1075635878abb55c82093cd7f9c8.
// - Task ID: 697d0b6ab0e8d9f5e26c29cf.
// - Task Root ID: 697ce4c0b1b5b2f302cb9e32.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";







/**
 * Enumeration for AudiobookCategoriesItem
 */
export enum AudiobookCategoriesItem {
  Unspecified = 0,
}
/**
 * Enumeration for AudiobookCategory
 */
export enum AudiobookCategory {
  Unspecified = 0,
  Ficcao = 1,
  NaoFiccao = 2,
  Literatura = 3,
  Autoajuda = 4,
  Empreendedorismo = 5,
}



/**
 * Interface for AudiobookModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface AudiobookModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  title: string;
  cover_image_url: string;
  audio_file_url: string;
  duration?: string | null;
  categories?: any[] | null;
  category: AudiobookCategory;
}

/**
 * ORM class for Audiobook entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class AudiobookORM {
  private static instance: AudiobookORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019c0fdf131574d48997076a9546a8eb';
    this.entityName = 'audiobook';
    this.entityVersion = '102019c1075635878abb55c82093cd7f9c8';
    this.taskId = '697d0b6ab0e8d9f5e26c29cf';
    this.taskRootId = '697ce4c0b1b5b2f302cb9e32';
  }

  /**
   * Get singleton instance of AudiobookORM
   */
  public static getInstance(): AudiobookORM {
    if (!AudiobookORM.instance) {
      AudiobookORM.instance = new AudiobookORM();
    }
    
    return AudiobookORM.instance;
  }

  /**
   * Get audiobook by IDs
   * Use this as a batch operation to get multiple records at once.
   */
  async getAudiobookByIDs(ids: string[]): Promise<AudiobookModel[]> {
    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete audiobook by IDs
   * Use this as a batch operation to delete multiple records at once.
   */
  async deleteAudiobookByIDs(ids: string[]): Promise<void> {
    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      ids: ids,
      format: {
        structured: true
      }
    });
  }

  /**
   * Get all Audiobook records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllAudiobook(): Promise<AudiobookModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new Audiobook record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertAudiobook(data: AudiobookModel[]): Promise<AudiobookModel[]> {
    const structured = data.map((item) => CreateData(AudiobookModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all Audiobook records
   */
  async purgeAllAudiobook(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List Audiobook records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listAudiobook(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[AudiobookModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get audiobook by Id index
   * This function gets data by index.
   */
  async getAudiobookById(
    id: string,
  ): Promise<AudiobookModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) audiobook by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setAudiobookById(
    id: string,
    data: AudiobookModel
  ): Promise<AudiobookModel[]> {
    const index = createIndexId(
      id
    );

    const values = AudiobookModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete audiobook by Id index
   */
  async deleteAudiobookById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get audiobook by DataCreator index
   * This function gets data by index.
   */
  async getAudiobookByDataCreator(
    data_creator: string,
  ): Promise<AudiobookModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) audiobook by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setAudiobookByDataCreator(
    data_creator: string,
    data: AudiobookModel
  ): Promise<AudiobookModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = AudiobookModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete audiobook by DataCreator index
   */
  async deleteAudiobookByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get audiobook by DataUpdater index
   * This function gets data by index.
   */
  async getAudiobookByDataUpdater(
    data_updater: string,
  ): Promise<AudiobookModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) audiobook by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setAudiobookByDataUpdater(
    data_updater: string,
    data: AudiobookModel
  ): Promise<AudiobookModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = AudiobookModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete audiobook by DataUpdater index
   */
  async deleteAudiobookByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get audiobook by Title index
   * This function gets data by index.
   */
  async getAudiobookByTitle(
    title: string,
  ): Promise<AudiobookModel[]> {
    const index = createIndexTitle(
      title
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) audiobook by Title index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setAudiobookByTitle(
    title: string,
    data: AudiobookModel
  ): Promise<AudiobookModel[]> {
    const index = createIndexTitle(
      title
    );

    const values = AudiobookModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete audiobook by Title index
   */
  async deleteAudiobookByTitle(
    title: string
  ): Promise<void> {
    const index = createIndexTitle(
      title
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to AudiobookModel data array
   */
  private resultToData(values: Data[]): AudiobookModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return AudiobookModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as AudiobookModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized AudiobookModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is AudiobookModel => item !== null);
  }
}

/**
 * Convert AudiobookModel data to Value array
 */
function AudiobookModelToValues(data: AudiobookModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'title', type: DataType.string, defaultValue: '' },
    { key: 'cover_image_url', type: DataType.string, defaultValue: '' },
    { key: 'audio_file_url', type: DataType.string, defaultValue: '' },
    { key: 'duration', type: DataType.string, defaultValue: null },
    { key: 'categories', type: DataType.array, defaultValue: null },
    { key: 'category', type: DataType.enumeration, defaultValue: 0 },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof AudiobookModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to AudiobookModel data
 */
function AudiobookModelFromValues(values: Value[]): AudiobookModel {
  const data: Partial<AudiobookModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'title':
        data.title = ParseValue(value, DataType.string) as string;
        break;
      case 'cover_image_url':
        data.cover_image_url = ParseValue(value, DataType.string) as string;
        break;
      case 'audio_file_url':
        data.audio_file_url = ParseValue(value, DataType.string) as string;
        break;
      case 'duration':
        data.duration = ParseValue(value, DataType.string) as string | null;
        break;
      case 'categories':
        data.categories = ParseValue(value, DataType.array) as any[] | null;
        break;
      case 'category':
        data.category = ParseValue(value, DataType.enumeration) as AudiobookCategory;
        break;
    }
  }
  
  return data as AudiobookModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}
/**
 * Create index for Title fields
 */
function createIndexTitle(
  title: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, title, 'title'),
  ];

  return {
    fields: ['title'],
    values
  };
}

export default AudiobookORM;